<feat>: commit parcial de la creación de entidad JiraUser
Porque se hace este cambio: Dada la integración se crea la base de la arquitectura a modo de template, tener en cuenta que solo se hizo para agilizar el proceso de desarrollo y posteriormente luego de crear toda la base de entidades procederemos con el tdd ajustando todo lo que sea necesario.

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -18,6 +18,14 @@ repos:
     rev: v0.0.2
     hooks:
       - id: install-dependencies
+      - id: phpcbf-subdir
+        args: [
+          'src',
+          '--extensions=php',
+          '--standard=PSR12',
+          '--ignore= src/vendor, src/storage, src/bootstrap, src/resources, src/tests, src/public, src/config, src/app/Helpers/helpers, bin',
+          'src'
+        ]
       - id: phpcs-subdir
         args: [
           'src',
@@ -27,14 +35,25 @@ repos:
           '--standard=PSR12',
           '--ignore= src/vendor, src/storage, src/bootstrap, src/resources, src/tests, src/public, src/config, src/app/Helpers/helpers, bin'
         ]
-      - id: phpcbf-subdir
-        args: [
-          'src',
-          '--extensions=php',
-          '--standard=PSR12',
-          '--ignore= src/vendor, src/storage, src/bootstrap, src/resources, src/tests, src/public, src/config, src/app/Helpers/helpers, bin',
-          'src'
-        ]
       - id: phpstan-subdir
         args: ['src']
         files: ^src/.*\.(php)$
+
+  - repo: local
+    hooks:
+      # PHPUnit Hook for Backend Testing
+      - id: phpunit
+        name: Test Backend with PhpUnit
+        entry: >
+          bash -c 'output=$(docker-compose run --rm artisan test);
+                   if echo "$output" | grep -q "FAILED"; then
+                     endPosition=$(echo "$output" | grep "FAILED" -A 50 | cut -d: -f1);
+                     echo -e "${endPosition}";
+                     exit 1;
+                   else
+                     exit 0;
+                   fi'
+        language: system
+        files: ^src/tests/.*\.(php)$
+        pass_filenames: false
+
